######################################################################
# Automatically generated by qmake (2.01a) Fri Jan 22 00:32:41 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += myMainWindow.h myModel.h
FORMS += myMainWindow.ui
SOURCES += main.cpp myMainWindow.cpp.cc myModel.cpp
